package com.example.MiniAssignmentOne.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "movies")
public class Movie {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey

    @DynamoDBAttribute
    private String title;
    @DynamoDBAttribute
    private String imdb_title_id;
    @DynamoDBAttribute
    private String original_title;
    @DynamoDBAttribute
    private int year;
    @DynamoDBAttribute
    private String date_published;
    @DynamoDBAttribute
    private String genre;
    @DynamoDBAttribute
    private int duration;
    @DynamoDBAttribute
    private String country;
    @DynamoDBAttribute
    private String language;
    @DynamoDBAttribute
    private String director;
    @DynamoDBAttribute
    private String writer;
    @DynamoDBAttribute
    private String production_company;
    @DynamoDBAttribute
    private String actors;
    @DynamoDBAttribute
    private double description;
    @DynamoDBAttribute
    private  int votes;
    @DynamoDBAttribute
    private String budget;
    @DynamoDBAttribute
    private String usa_gross_income ;
    @DynamoDBAttribute
    private String worlwide_gross_income;
    @DynamoDBAttribute
    private String metascore;
    @DynamoDBAttribute
    private  int reviews_from_users;
    @DynamoDBAttribute
    private int reviews_from_critics;


    public void setDatePublished(String datum) {
    }

    public void setOriginalTitle(int i) {
    }

    public void setImdbTitleId(String datum) {
    }

    public void setProductionCompany(String datum) {
    }

    public void setWorldwideGrossIncome(String datum) {
    }

    public void setUsaGrossIncome(String datum) {
    }

    public void setReviewsFromUsers(int i) {
    }

    public void setReviewsFromCritics(int i) {
    }
    public void setOriginalTitle(String originalTitle) {
        this.original_title = originalTitle;
    }

}